DermaMNIST:
    data_dir: D:/Ark/Ark_MICCAI2023/medmnist/224X224
    train_list: D:/medmnist/224X224/dermamnist/dermamnist_train.csv
    val_list: D:/medmnist/224X224/dermamnist/dermamnist_val.csv
    test_list: D:/medmnist/224X224/dermamnist/dermamnist_test.csv
    diseases: ['actinic keratoses and intraepithelial carcinoma', 'basal cell carcinoma', 'benign keratosis-like lesions', 'dermatofibroma', 'melanoma', 'melanocytic nevi', 'vascular lesions']
    task_type: multi-class classification